server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://103.217.220.184:3306/rainbow_ats
    username: rainbow_ats_user
    password: rainbow-ats-pwd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
  security:
    Oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bassure
          jwk-set-uri: http://localhost:8080/realms/bassure/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: atsReact
      principal-attribute: preferred_username

ats:
  response:
    error-key: errors
    success: Operation completed successfully
    error: failed
    delete-message: deleted successfully..!
    edit-message: edited Successfully ...!
    add-message: added Successfully ...!
    already-exists: already exists ...!
    no-data-found: No data to show
    skill-not-found: Skill not found...!
    server-error: Server error, try again later!!
    updation-failed: You can''t decrease the assigned task ..!
    message: message
    reschedule: interview rescheduled successfully ...!
    no-interview-scheduled-previously: no Interview Scheduled Previously
    applicantServiceBaseEmailUrl: http://localhost:8083/Application-tracking-system/email/api
    otpUrl: http://localhost:3000/Candidates/otp?email=
    tenantBaseUrl: https://dev.rainbow.bassure.in/api/tenant-mgmt


  codes:
    success: 2200
    failed: 2250
    not-valid: 2252
    not-found: 2152
    server-error: 2254
    constraint-error: 2255
    already-exists: 2256
    no-change-required: 2203
  tenentmanagement:
    tenant-service-url: "https://dev.rainbow.bassure.in/api/tenant-mgmt"
    view-one-employee: /view-single-employee
    get-id-by-role: /getidbyrole
    get-emp-by-role: /get-employee-by-role
    role: role
    recruiter: Recruiter
    interviewer: Interviewer
    get-employeeby-ids: /getemployeebyids
    ids: ids

applicantInterviewSubject: Interview Scheduled For You
interviewscheduleBody: Hi, \n An Interview has been scheduled to You
interviewerMailSubject: You have an Interview Schedule
interviewerMailBody: An Interview will be scheduled to You